// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZSLJNmT6z0nbKru8LNfiIJjn8_7xqdMI',
    appId: '1:247869205432:web:c067dffb3773ac03be3d4d',
    messagingSenderId: '247869205432',
    projectId: 'bro-golf1',
    authDomain: 'bro-golf1.firebaseapp.com',
    storageBucket: 'bro-golf1.appspot.com',
    measurementId: 'G-ZN4Q1YQWF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe1egiX_hxHkzQQgL47HzBlL7L51zj6Ho',
    appId: '1:247869205432:android:5ddd000ff63bc98fbe3d4d',
    messagingSenderId: '247869205432',
    projectId: 'bro-golf1',
    storageBucket: 'bro-golf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLyKjl4GBZ4OM2Kkx5T9vcqTZOtviqIz0',
    appId: '1:247869205432:ios:1e627d51ad48a611be3d4d',
    messagingSenderId: '247869205432',
    projectId: 'bro-golf1',
    storageBucket: 'bro-golf1.appspot.com',
    iosBundleId: 'com.example.brogolf1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLyKjl4GBZ4OM2Kkx5T9vcqTZOtviqIz0',
    appId: '1:247869205432:ios:02b746ae244b1b7ebe3d4d',
    messagingSenderId: '247869205432',
    projectId: 'bro-golf1',
    storageBucket: 'bro-golf1.appspot.com',
    iosBundleId: 'com.example.brogolf1.RunnerTests',
  );
}
